version: '3'
services:
    selenium-hub:
        image: selenium/hub:3.141.59-gold
        container_name: selenium-hub
        ports:
          - "4444:4444"
    chrome:
        image: selenium/node-chrome:3.141.59-gold
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        volumes:
          - /dev/shm:/dev/shm
